[package]
name = "server-kit-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.0.2"

[build-dependencies]
glob = "0.3.0"
protobuf-codegen = "3.0.2"
